# Generated by Django 3.2.9 on 2022-03-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.IntegerField()),
                ('phi', models.IntegerField()),
            ],
        ),
    ]
